#!/bin/bash
#
# Helper functions for "update" scripts.
#
# (c) Copyright 2020 Matthew Barnes <mbarnes@redhat.com>
#

function flac2vorbis {
  SRCDIR=$(dirname "$1")
  DSTDIR=$2
  FLACNAME=$(basename "$1")
  VORBISNAME=$(echo ${FLACNAME/%flac/ogg} | sed -e "s|\?||g" -e "s|:| -|g")
  if ! gio list "$DSTDIR" | grep --quiet "$VORBISNAME"
  then
    ffmpeg -nostats -loglevel quiet -i "$SRCDIR/$FLACNAME" \
           -qscale:a 0 -map 0:a -y "$SRCDIR/$VORBISNAME"
    gio move "$SRCDIR/$VORBISNAME" "$DSTDIR"
    echo "$DSTDIR/$VORBISNAME"
  fi
}

function copyflac {
  SRCDIR=$1
  DSTDIR=$(echo "$SRCDIR" | sed -e "s|:| -|g" -e "s|\*||g" -e "s|$HOME|$DEVICEPATH|")
  export DSTDIR
  gio mkdir --parent "$DSTDIR" 2> /dev/null
  find "$SRCDIR" -name "*.flac" -maxdepth 1 -print0 | \
    xargs --null --max-procs 0 --replace bash -c 'flac2vorbis "{}" "$DSTDIR"'
}

function check_library_size {
  LIBRARYMAX=$1
  SIZE=$(find "$DEVICEPATH/Music" -type f | wc --lines)
  if (( SIZE > LIBRARYMAX ))
  then
    echo "WARNING: Library size exceeds maximum by $(( SIZE - LIBRARYMAX )) files" > /dev/stderr
  fi
}
