#!/bin/bash
#
# This script synchronizes a Sansa Clip Jam device by generating Ogg Vorbis
# (.ogg) files from local FLAC files and moving them to the device so as to
# preserve the directory layout of the FLAC files.
#
# (c) Copyright 2020 Matthew Barnes <mbarnes@redhat.com>
#

set -euo pipefail

source $(dirname $(realpath $(which $0)))/functions

export DEVICEPATH="/media/$USER/MUSIC"

export -f flac2vorbis
export -f copyflac

if [ ! -d "$DEVICEPATH" ]
then
  >&2 echo "Sansa Clip Jam device not mounted."
  exit 1
fi

STARTDIR="$HOME/Music"
if [[ $(pwd) == "$STARTDIR"* ]]
then
  STARTDIR=$(pwd)
fi

find "$STARTDIR" -name "*.flac" -print0 | \
  xargs --null dirname --zero | \
  uniq --zero-terminated | \
  xargs --null --replace bash -c 'copyflac "{}"'

# Device can only index up to 2000 files.
check_library_size 2000
