#!/bin/bash
#
# This script syncrhonizes an Android device with an integrated SD card by
# generating Ogg Vorbis (.ogg) files from local FLAC files and moving them
# to the device so as to preserve the directory layout of the FLAC files.
#
# (c) Copyright 2020 Matthew Barnes <mbarnes@redhat.com>
#

set -euo pipefail

source $(dirname $(realpath $(which $0)))/functions

export MOUNTURL="$(gio mount --list | grep ^Mount | grep --only-matching 'mtp://.*/')"
export DEVICEPATH="${MOUNTURL}Card"

export -f flac2vorbis
export -f copyflac

if [ ! -n "$MOUNTURL" ]
then
  >&2 echo "Android device with SD card not mounted."
  exit 1
fi

STARTDIR="$HOME/Music"
if [[ $(pwd) == "$STARTDIR"* ]]
then
  STARTDIR=$(pwd)
fi

find "$STARTDIR" -name "*.flac" -print0 | \
  xargs --null dirname --zero | \
  uniq --zero-terminated | \
  xargs --null --replace bash -c 'copyflac "{}"'
